name: C++ CI
on: [push]
jobs:
  Build-and-Test:
    runs-on: ubuntu-20.04
    container:
        image: robotma/focal-dev-qianli:latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Environement
        run: pwd && echo $USER
      - name: Compile
        run: |
          cd .. && mkdir tmpBuild && cd tmpBuild
          cmake -G Ninja ../HighwayRoadMap && ninja -j 9
      - name: Test
        run: cd ../tmpBuild && ctest

  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name  }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os  }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref  }} and your repository is ${{ github.repository  }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository  }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace  }}
      - run: echo "ğŸ This job's status is ${{ job.status  }}."

